### ISSUE TITLE
[BUG] not work on typescript and golang

### ISSUE THREAD

**Issue by windwp** [PascalSenn/keyboard-quickfix#1]
your extension not work.
I think it have mistake 
https://github.com/PascalSenn/keyboard-quickfix/blob/f15df3754740c1c807151a56958890bbbb79d251/src/extension.ts#L40
i change it and it work.
```typescript
  constructor(command: CodeActionCommand) {
    this.command = command;
    this.label = command.title;
    if (typeof command.command !== "string") {
      this.command = command.command as CodeActionCommand;
    }
  }
```

it will better if i can hide the label when i select command

**Comment by aabccd021** [comment]
It also doen't work on flutter.

**Comment by h7x4ABk3g** [comment]
@windwp Could you submit a pull request?

**Comment by PascalSenn** [comment]
hi threre, sorry for the long response time, quite busy these days. 
I am happily gonna except the pull request. Do you mind removing the package-lock.json?

**Comment by PascalSenn** [comment]
Should be available:
https://marketplace.visualstudio.com/items?itemName=pascalsenn.keyboard-quickfix

Thanks for the contribution ❤
